artifact_uri: file:///D:/Projects/Software/Erasmus-Scholarship-grant-prediction-engine/notebooks/3_model_training_and_evaluation/../../models/876244644968357782/b8527037aa204e4793f5405c3ff5f7e4/artifacts
end_time: 1720378896162
entry_point_name: ''
experiment_id: '876244644968357782'
lifecycle_stage: active
run_id: b8527037aa204e4793f5405c3ff5f7e4
run_name: Custom Settings Model
run_uuid: b8527037aa204e4793f5405c3ff5f7e4
source_name: ''
source_type: 4
source_version: ''
start_time: 1720378893080
status: 3
tags: []
user_id: harde
