artifact_location: file:///D:/Projects/Software/Erasmus-Scholarship-grant-prediction-engine/notebooks/3_model_training_and_evaluation/../../models/876244644968357782
creation_time: 1720378888195
experiment_id: '876244644968357782'
last_update_time: 1720378888195
lifecycle_stage: active
name: Erasmus Scholarship Grant Prediction Engine
